mkdir -p -v Data/Images/Original/Train/
mkdir -p -v Data/Images/Original/Test/
mkdir -p -v Data/Images/Original/Validation/
mkdir -p -v Data/Images/224/Train/
mkdir -p -v Data/Images/224/Test/
mkdir -p -v Data/Images/224/Validation/
mkdir -p -v Data/Images/299/Train/
mkdir -p -v Data/Images/299/Test/
mkdir -p -v Data/Images/299/Validation/
mkdir -p -v Data/Features/224/Train/
mkdir -p -v Data/Features/224/Test/
mkdir -p -v Data/Features/224/Validation/
mkdir -p -v Data/Features/299/Train/
mkdir -p -v Data/Features/299/Test/
mkdir -p -v Data/Features/299/Validation/
mkdir -p -v Data/Json/
mkdir -p -v Scripts/Model/Help/
mkdir -p -v Scripts/Preprocessing/Help/
mkdir -p -v Scripts/Feature_Extraction/Help/
mkdir -p -v Scripts/Other/Help
mkdir -p -v Logs/Tensorflow/Tensorboard/Graphs
mkdir -p -v Logs/Tensorflow/Tensorboard/Loss
mkdir -p -v Logs/Tensorflow/Tensorboard/Accuracy
mkdir -p -v Logs/Summary/
mkdir -p -v Logs/Snapshots/
mkdir -p -v Logs/Timestamp/
